package clientes

type Cliente struct {
	Uid                        string        `json:"uid"`
	IDComercio                 int64         `json:"id_comercio"`
	Cedula                     string        `json:"cedula"`
	IDTipoDocumento            int64         `json:"id_tipo_documento"`
	TipoDocumento              string        `json:"tipo_documento"`
	Nombre                     string        `json:"nombre"`
	Apellido                   string        `json:"apellido"`
	Fullname                   string        `json:"fullname"`
	Email                      string        `json:"email"`
	Celular                    string        `json:"celular"`
	Genero                     string        `json:"genero"`
	FechaRegistroLeal          string        `json:"fecha_registro_leal"`
	FechaRegistroComercio      string        `json:"fecha_registro_comercio"`
	Cumpleanos                 string        `json:"cumpleanos"`
	CumpleanosMes              int64         `json:"cumpleanos_mes"`
	CumpleanosDia              int64         `json:"cumpleanos_dia"`
	GrupoEdad                  string        `json:"grupo_edad"`
	Edad                       int64         `json:"edad"`
	EstadoLeal                 string        `json:"estado_leal"`
	EstadoComercio             string        `json:"estado_comercio"`
	PlataformaMovil            interface{}   `json:"plataforma_movil"`
	EnvioMailGlobal            int64         `json:"envio_mail_global"`
	EnvioMail                  int64         `json:"envio_mail"`
	EnvioSMSGlobal             int64         `json:"envio_sms_global"`
	EnvioSMS                   int64         `json:"envio_sms"`
	EnvioPushGlobal            int64         `json:"envio_push_global"`
	EnvioPushComercio          int64         `json:"envio_push_comercio"`
	FechaPerfilCompletado      string        `json:"fecha_perfil_completado"`
	IDCiudad                   int64         `json:"id_ciudad"`
	Ciudad                     string        `json:"ciudad"`
	CodPais                    string        `json:"cod_pais"`
	IDDepartamento             int64         `json:"id_departamento"`
	PuntosActivos              int64         `json:"puntos_activos"`
	PuntosVencidos             int64         `json:"puntos_vencidos"`
	PuntosUsados               int64         `json:"puntos_usados"`
	PuntosTotales              int64         `json:"puntos_totales"`
	PuntosPorVencer            int64         `json:"puntos_por_vencer"`
	IDEstatus                  int64         `json:"id_estatus"`
	Estatus                    string        `json:"estatus"`
	UltimaCalificacion         int64         `json:"ultima_calificacion"`
	PremiosDisponiblesCantidad int64         `json:"premios_disponibles_cantidad"`
	IDPremiosDisponibles       string        `json:"id_premios_disponibles"`
	PremiosDisponibles         string        `json:"premios_disponibles"`
	BlackList                  int64         `json:"black_list"`
	PremiosPorVencer           int64         `json:"premios_por_vencer"`
	EstadoUsuario              string        `json:"estadoUsuario"`
	TotalTx                    int64         `json:"totalTx"`
	TicketPromedio             int64         `json:"ticket_promedio"`
	Frecuencia                 float64       `json:"frecuencia"`
	GastoTotal                 int64         `json:"gasto_total"`
	IDSucursal                 []int64       `json:"id_sucursal"`
	IDPremioReclamados         interface{}   `json:"id_premio_reclamados"`
	PremiosReclamados          interface{}   `json:"premios_reclamados"`
	PremiosReclamadosCantidad  int64         `json:"premios_reclamados_cantidad"`
	Transacciones              int64         `json:"transacciones"`
	Banderazos                 int64         `json:"banderazos"`
	Cargas                     int64         `json:"cargas"`
	Redenciones                int64         `json:"redenciones"`
	Visitas                    int64         `json:"visitas"`
	UltimaVisita               string        `json:"ultima_visita"`
	UltimaVisitaDias           int64         `json:"ultima_visita_dias"`
	UltimaVisitaHoras          int64         `json:"ultima_visita_horas"`
	FechaUltimaCalificacion    interface{}   `json:"fecha_ultima_calificacion"`
	Productos                  []string      `json:"productos"`
	Etiquetas                  []interface{} `json:"etiquetas"`
	Categorias                 []interface{} `json:"categorias"`
}
